replicas: 1
imagePullSecrets:
  name: ghcr-secret
image:
  repository: ghcr.io/jeffersondossantosaguiar/task-api
  tag: v1.0.0
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
config:
  dbHost: postgres
  dbName: taskdb
